.. _builtin-handler-simpleHandler: _static/groovydoc/org/rackspace/gdeproxy/Handlers.html#simpleHandler(org.rackspace.gdeproxy.Request)
.. _builtin-handler-echoHandler: _static/groovydoc/org/rackspace/gdeproxy/Handlers.html#echoHandler(org.rackspace.gdeproxy.Request)
.. _builtin-handler-Delay: _static/groovydoc/org/rackspace/gdeproxy/Handlers.html#Delay(int,%20def)
.. _builtin-handler-Route: _static/groovydoc/org/rackspace/gdeproxy/Handlers.html#Route(java.lang.String,%20int,%20boolean,%20org.rackspace.gdeproxy.ClientConnector)

