
.. _simpleHandler: _static/groovydoc/org/rackspace/deproxy/Handlers.html#simpleHandler(org.rackspace.deproxy.Request)
.. _echoHandler: _static/groovydoc/org/rackspace/deproxy/Handlers.html#echoHandler(org.rackspace.deproxy.Request)
.. _Delay: _static/groovydoc/org/rackspace/deproxy/Handlers.html#Delay(int,%20def)
.. _Route: _static/groovydoc/org/rackspace/deproxy/Handlers.html#Route(java.lang.String,%20int,%20boolean,%20org.rackspace.deproxy.ClientConnector)

.. _Route: _static/groovydoc/org/rackspace/deproxy/Handlers.html#Route(java.lang.String,%20int,%20boolean,%20org.rackspace.deproxy.ClientConnector)

.. _Deproxy: _static/groovydoc/org/rackspace/deproxy/Deproxy.html
.. _makeRequest: _static/groovydoc/org/rackspace/deproxy/Deproxy.html#makeRequest(java.lang.String,%20java.lang.String,%20def,%20java.lang.String,%20java.lang.String,%20def,%20def,%20def,%20java.util.Map,%20boolean,%20boolean,%20org.rackspace.deproxy.ClientConnector)
.. _addEndpoint: _static/groovydoc/org/rackspace/deproxy/Deproxy.html#addEndpoint(int,%20java.lang.String,%20java.lang.String,%20def)
.. _shutdownDeproxy: _static/groovydoc/org/rackspace/deproxy/Deproxy.html#shutdown()

.. _Endpoint: _static/groovydoc/org/rackspace/deproxy/Endpoint.html
.. _handleRequest: _static/groovydoc/org/rackspace/deproxy/Endpoint.html#handleRequest(org.rackspace.deproxy.Request,%20java.lang.String)
.. _shutdownEndpoint: _static/groovydoc/org/rackspace/deproxy/Endpoint.html#shutdown()

.. _Request: _static/groovydoc/org/rackspace/deproxy/Request.html

.. _Response: _static/groovydoc/org/rackspace/deproxy/Response.html

.. _HeaderCollection: _static/groovydoc/org/rackspace/deproxy/HeaderCollection.html

.. _Handling: _static/groovydoc/org/rackspace/deproxy/Handling.html

.. _MessageChain: _static/groovydoc/org/rackspace/deproxy/MessageChain.html
.. _handlings: _static/groovydoc/org/rackspace/deproxy/MessageChain.html#handlings
.. _orphanedHandlings: _static/groovydoc/org/rackspace/deproxy/MessageChain.html#orphanedHandlings

.. _ClientConnector: _static/groovydoc/org/rackspace/deproxy/ClientConnector.html
.. _sendRequest: _static/groovydoc/org/rackspace/deproxy/ClientConnector.html#sendRequest(org.rackspace.deproxy.Request,%20boolean,%20def,%20def,%20org.rackspace.deproxy.RequestParams)
.. _BareClientConnector: _static/groovydoc/org/rackspace/deproxy/BareClientConnector.html
.. _DefaultClientConnector: _static/groovydoc/org/rackspace/deproxy/DefaultClientConnector.html

.. _RequestParams: _static/groovydoc/org/rackspace/deproxy/RequestParams.html
.. _sendDefaultRequestHeaders: _static/groovydoc/org/rackspace/deproxy/RequestParams.html#sendDefaultRequestHeaders
.. _usedChunkedTransferEncoding_req: _static/groovydoc/org/rackspace/deproxy/RequestParams.html#usedChunkedTransferEncoding

.. _HandlerContext: _static/groovydoc/org/rackspace/deproxy/HandlerContext.html
.. _sendDefaultResponseHeaders: _static/groovydoc/org/rackspace/deproxy/HandlerContext.html#sendDefaultResponseHeaders
.. _usedChunkedTransferEncoding_resp: _static/groovydoc/org/rackspace/deproxy/HandlerContext.html#usedChunkedTransferEncoding

.. _ServerConnector: _static/groovydoc/org/rackspace/deproxy/ServerConnector.html
.. _SocketServerConnector: _static/groovydoc/org/rackspace/deproxy/SocketServerConnector.html
.. _shutdownSocketServerConnector: _static/groovydoc/org/rackspace/deproxy/SocketServerConnector.html#shutdown()
.. _ServletServerConnector: _static/groovydoc/org/rackspace/deproxy/ServletServerConnector.html
