
.. _builtin-handler-simpleHandler: _static/groovydoc/org/rackspace/gdeproxy/Handlers.html#simpleHandler(org.rackspace.gdeproxy.Request)
.. _builtin-handler-echoHandler: _static/groovydoc/org/rackspace/gdeproxy/Handlers.html#echoHandler(org.rackspace.gdeproxy.Request)
.. _builtin-handler-Delay: _static/groovydoc/org/rackspace/gdeproxy/Handlers.html#Delay(int,%20def)
.. _builtin-handler-Route: _static/groovydoc/org/rackspace/gdeproxy/Handlers.html#Route(java.lang.String,%20int,%20boolean,%20org.rackspace.gdeproxy.ClientConnector)

.. _Deproxy: _static/groovydoc/org/rackspace/gdeproxy/Deproxy.html
.. _makeRequest: _static/groovydoc/org/rackspace/gdeproxy/Deproxy.html#makeRequest(java.lang.String,%20java.lang.String,%20def,%20def,%20def,%20java.util.Map,%20boolean,%20boolean,%20org.rackspace.gdeproxy.ClientConnector)
.. _addEndpoint: _static/groovydoc/org/rackspace/gdeproxy/Deproxy.html#addEndpoint(int,%20java.lang.String,%20java.lang.String,%20def)
.. _shutdown: _static/groovydoc/org/rackspace/gdeproxy/Deproxy.html#shutdown()

.. _DeproxyEndpoint: _static/groovydoc/org/rackspace/gdeproxy/DeproxyEndpoint.html

.. _Request: _static/groovydoc/org/rackspace/gdeproxy/Request.html

.. _Response: _static/groovydoc/org/rackspace/gdeproxy/Response.html

.. _Handling: _static/groovydoc/org/rackspace/gdeproxy/Handling.html

.. _MessageChain: _static/groovydoc/org/rackspace/gdeproxy/MessageChain.html
.. _orphanedHandlings: _static/groovydoc/org/rackspace/gdeproxy/MessageChain.html#orphanedHandlings